### ISSUE TITLE
Provide live demo

### ISSUE THREAD

**Issue by wokier** [moxiecode/moxie#100]
It would be helpfull to have a live demo showing how to use it.
It would complete the https://github.com/moxiecode/moxie/wiki/File-Picker doc.
Especially on the FormData part.
In my case, i would like to emulate FormData for Internet Explorer 9, but with a regular file upload input button. Is that possible ?

**Comment by jayarjo** [comment]
Best example of how to use mOxie is probably is [Plupload](https://github.com/moxiecode/plupload/blob/b5da3bf6f0ea555dbc6c604f141c643ca4352062/src/plupload.js#L2409).
