### ISSUE TITLE
Some problems with Blob slice() and file getNative() in Flash / HTML4 runtime

### ISSUE THREAD

**Issue by hectorguo** [moxiecode/moxie#102]
I'm using `FileReader` to add a function that can **get file signatures and identify the actual type of a file**.
However, when i test it in `Flash` and `HTML4` runtime, the trouble comes. 
Here is the code:
```javascript
/**
 * Read the file content and check the signatrue
 * @param  {object}   file   file object published by mOxie
 * @param  {function}   onLoad callbacks
 */
checkFileSignature: function(file, onLoad) {
    var ext = mOxie.Mime.getFileExtension(file.name) || 'none',
        fileSign = mOxie.Mime.signatures[ext] || {
            offset: 0,
            sizet: 4
        },
        blob = new mOxie.Blob(file.getSource().ruid, file.getSource().getSource()),
        slice = blob.slice(fileSign.offset, fileSign.offset + fileSign.sizet), // slice file from offset to sizet
        reader = new mOxie.FileReader();
    reader.onload = function() {
        var binaryBuffer = reader.result, // The result binaryString
            signature = [], // Read 4 or 8 bytes, big-endian
            isMatch = false; // whether file signature match with the source file type

        // get Hex String of file Signatrue
        for (var i = 0; i < binaryBuffer.length; i++) {
            var tmp = binaryBuffer.charCodeAt(i);
            signature += (tmp >> 4).toString(16);
            signature += (tmp & 0xF).toString(16);
        };
        signature = signature.toUpperCase();
        if (!$.isArray(fileSign.signature)) {
            fileSign.signature = [fileSign.signature];
        }
        if ($.inArray(signature, fileSign.signature) !== -1) {
            isMatch = true;
        }
        onLoad(isMatch, signature);
    };
    reader.readAsBinaryString(slice); // Read the slice of the file
}
mOxie.Mime.signatures = {
    zip: {
        signature: "504B0304",
        offset: 0,
        sizet: 4
    },
    rar: {
        signature: "52617221",
        offset: 0,
        sizet: 4
    },
    ... 
}
```

Below are the problems:
### Runtime Flash Issue
**1. `file.getNative()` return `null`, but the file exist with an object.**
When i select a file and add a breakpoint on the `file.getNative()`, I find that it returns `null`.  
But when i change it to `file.getSource().getSource()`,  it returns a file object. And it can really read.
I find the `getNative` method only judge whether the file is a **blob** or a **file**.
Is this a bug or i miss something?

**2. FileReader result return a weird value**
At first time, I select a file `xxx.zip`, and get the `reader.result`,  it work well. 
the signature(hex string) is: `"50 4B 03 04"`
But when I delete it from the queue and select the file again, the result return **a superposition of string**. 
the signature is: `"50 4B 03 04 50 4B 03 04"`
And when I select the file again and again, the result become longer. 
like this: `"50 4B 03 04 50 4B 03 04 50 4B 03 04"`
It looks like the old file not be deleted.
This problem only appear in `Flash` runtime.

### Runtime HTML4 Issue
**1. Blob `slice` can not work**
I new a `Blob()` object,and it works well.
But when I use the `blob.slice(0, 4)`,  it return `undefined`. 

The codes works well in `HTML5` runtime.
Hope to receive the answer. Tks!

**Comment by jayarjo** [comment]
Since we have a fresh release now, closing this.
