### ISSUE TITLE
window.btoa throw a error 

### ISSUE THREAD

**Issue by SunLn** [moxiecode/moxie#111]
My code is 
```
     URLSafeBase64Encode: function(v) {
            v = mOxie.btoa(v);
            return v.replace(/\//g, '_').replace(/\+/g, '-');
        }
```

 when v is Chinese,like window.btoa('你好，世界') , btoa will throw a error .

```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

It is caused by 

https://github.com/moxiecode/moxie/blob/3e0475c18fedaed7145f897ad314cea33d80150d/src/javascript/core/utils/Encode.js#L122

How to solve it ?  If I dont't use the btoa fuc in Moxie, I have to import other lib fuc . But I donot want to do so . Can remove these codes in Moxie to solve problem.

```
		if (typeof(window.btoa) === 'function') {
			return window.btoa(data);
		}
```
If is allowed  , I wil make a PR .

Thanks very much .

**Comment by SunLn** [comment]
It is still not ok .And throw the same error.

**Comment by jayarjo** [comment]
Thanks for coming back and actually forcing us to fix this.
