### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ruid' of undefined while drag and drop

### ISSUE THREAD

**Issue by SathyaShetty** [moxiecode/moxie#113]
Hi,
I am using Moxie File upload and Drag and drop feature. File upload functionality is working fine in all browser even in IE9 also. But while reading the dropped file content, i am getting "Uncaught TypeError: Cannot read property 'ruid' of undefined "  error in all browser.(error in moxie.js line number:  2782)
my code snippet for drag and drop feature;

```
<div id="drop_zone">
    Drop files here
</div>
<br />
<div id="filelist"></div>

<script type="text/javascript">
    var fileDrop = new mOxie.FileDrop('drop_zone'), fileList = mOxie.get('filelist');

    fileDrop.ondrop = function() {
        mOxie.each(this.files, function(file) {
            loadAttachment(file);
        });
    };

    fileDrop.init();

  function loadAttachment(file)  {       	
         var reader = new mOxie.FileReader();
        reader.onloadend = function() {
		        alert(reader.result); // here it is not alerting content of file, instead throwing error as i                                             shown above.
        };
		        	    
     reader.onerror = function() {
		       reject(reader.error);
		 };
    reader.readAsBinaryString(file);
	}

</script>
```

Can anyone help me regarding this issue, Am strugling with this issue since 4 days..:(

Thanks in Advance.

**Comment by jayarjo** [comment]
Our fault. Do you know how to rebuild moxie js ([here](https://github.com/moxiecode/moxie#compile-js))?.. it should work properly now.

**Comment by SathyaShetty** [comment]
Thanks for your update on the same.
