### ISSUE TITLE
Image quality is poor when using Flash

### ISSUE THREAD

**Issue by hppycoder** [moxiecode/moxie#114]
The image quality obtained from Flash is extremely poor. I setup moxie, and have it working. The HTML5 version works great, but then when I forced it to use the Flash version (as I have to support IE9 in my project) I noticed the following poor image quality.

```javascript
var fileInput = new mOxie.FileInput({
          browse_button: document.getElementById('filePicker'), // or document.getElementById('file-picker')
          runtime_order: 'flash,silverlight',
          accept: [
            {title: 'Images', extensions: 'jpg,gif,png'} // accept only images
          ]
        });

        fileInput.onchange = function(e) {
          // do something to files array
          var file = e.target.files[0];

          var imagex = new mOxie.Image();
          imagex.onload = function() {
            var sourceImage = document.createElement("img");
            sourceImage.id = 'full-image';
            sourceImage.src = imagex.getAsDataURL();
            $('body').append(sourceImage);
          };
          imagex.load(file);
        };

        fileInput.init(); // initialize
```

Images it produces:
![Using Flash version](http://i.imgur.com/w2iDBze.png)

![Another awesome photo](http://i.imgur.com/Vfp8dk3.png)

Has anyone else had this issue? More importantly, can anyone share how to fix this? I cannot put this into production with the images looking like that from the uploads.

**Comment by jayarjo** [comment]
Images produced by Flash and HTML5 are comparable in quality. I'd say that what you acquire there might be an exception of some kind. Can you share originals, so that we could troubleshoot locally?

**Comment by hppycoder** [comment]
@jayarjo - I couldn't get Plnkr to take in the .swf correctly, I have then moved it to one of my other servers so you can see it. What I found is that if you use a PNG Flash works great, if you use a JPG though that's when things go wrong.

http://theeasyapi.com/moxietest.php

Let me know what you find, maybe there's an encoding on the flash application with jpg?

**Comment by hppycoder** [comment]
@jayarjo - Take a look at the PR I just put in, you can view the working example by going here:
http://theeasyapi.com/moxietest2.php

It is now working by using the full image without any quality alterations. I think a good feature we could add would be to tie the quality param back from JS into the Flex app to have it be controlled there. If that already exists then I didn't see that in any of the documentation and my apologies.

**Comment by jayarjo** [comment]
You can pass mime type and quality of resulting image in  `imagex.getAsDataURL();` like this:

```
sourceImage.src = imagex.getAsDataURL('image/jpeg', 90);
```

The comment on that function says that arguments are optional, but it looks like we never supplied any defaults there, so I'd say the comment is misleading at the moment. I think that quality defaulted not to 80 but to 0.

**Comment by hppycoder** [comment]
I think you are absolutely correct, it defaulted to 0 and not 80. Will you get your PR merged in? I think we are all set now with your changes.

**Comment by jayarjo** [comment]
Yes, it is in master now.

**Comment by hppycoder** [comment]
Thanks @jayarjo, that will close up this ticket now.

**Comment by jayarjo** [comment]
In case you cloned it or pulled in, update. Somehow I managed to sneak in a typo :/

**Comment by hppycoder** [comment]
When you fix the typo then could you update bower.json, then make another release?
