### ISSUE TITLE
the `browse_button` and the `container`  relationship?

### ISSUE THREAD

**Issue by icai** [moxiecode/moxie#118]
https://github.com/moxiecode/moxie/blob/547d817aab0c4aed7c850a0339e88ee65fa1e544/bin/js/moxie.js#L3438

`container` must contain `browse_button` ?

							pos = Dom.getPos(browseButton, Dom.get(options.container));
							size = Dom.getSize(browseButton);

**Comment by sambiomatters** [comment]
The browse button defines the element on which clicking should open the
file selection prompt. In actuality a hidden element is created in a new
dom element  (the container)  that is then overlayed over the button you
initially defined as the browse button. So when you think your clicking the
browse button you're actually clicking a hidden element with the exact
dimensions and position of the browse button that is in a container with a
higher z index on top of that button. This is needed for silverfish and
flash to work correctly.

**Comment by icai** [comment]
@sambiomatters  thanks your explain.
