### ISSUE TITLE
Preview an image file thumbnail in IE8 and IE9

### ISSUE THREAD

**Issue by masbicudo** [moxiecode/moxie#122]
I am trying to display a thumbnail of the selected image with the following code... it works in Chrome, IE 11, and all modern browsers. But I need it to work in IE8 and it fails:

Code

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="moxie.js"></script>
    <script>mOxie.Env.swf_url = 'Moxie.swf';</script>
    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new mOxie.FileReader();
                reader.onload = function (e) {
                    debugger;
                    $('#preview').attr('src', e.target.result).show();
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
</head>
<body>
    <form id="form1">
        <div id="container">
            <a id="file-picker" href="javascript:;">Browse...</a>
        </div>

        <script>
            var fileInput = new mOxie.FileInput({
                browse_button: 'file-picker', // or document.getElementById('file-picker')
                container: 'container',
                accept: [
                    {title: "Image files", extensions: "jpg,gif,png"} // accept only images
                ],
                multiple: true // allow multiple file selection
            });

            fileInput.onchange = function(e) {
                // do something to files array
                console.info(e.target.files); // or this.files or fileInput.files
                readURL(this);
            };

            fileInput.init(); // initialize
        </script>
        <img id="preview" 
             src="" 
             alt="" 
             style="display:none; max-width: 160px; max-height: 120px; border: none;"/>
    </form>
</body></html>
```

In IE8 it does not display the image:

(screenshot)
![image](https://cloud.githubusercontent.com/assets/1653710/6881744/741570fe-d54b-11e4-9699-b5d523e1d428.png)

In IE11 it shows it correctly:

![image](https://cloud.githubusercontent.com/assets/1653710/6881750/bef255d8-d54b-11e4-87df-2bbc288961e1.png)

I realize that this might be a proble with IE8 supporting data URL's... is there a way to do this using mOxie and not rely on data URL?

**Comment by zukilover** [comment]
I've just came across a similar problem. Turns out I've got a wrong path for the silverlight/flash.

**Comment by jayarjo** [comment]
Try moxies internal image wrapper, which has capability of embedding the thumb into the specified dom container. It can show thumbs even in IE6/7.

First you need to [load](https://github.com/moxiecode/moxie/wiki/Image#load-srcmixed-method) the image from the file object that you pick up using file input component. And then you [embed it](https://github.com/moxiecode/moxie/wiki/Image#embed-eloptstypeimagejpegquality90cropfalse-method).
