### ISSUE TITLE
Firefox Nightly 41 version is not detected

### ISSUE THREAD

**Issue by nazar-pc** [moxiecode/moxie#128]
In Firefox Nightly 41 version is detected as `NaN`, bug was introduced in 88faa45, if revert this change - everything works fine, otherwise click is not working (though Drag and Drop works fine).

IIt seems UA parser of version 0.6.2 is used (however it looks be patched anyway and mentioned commit didn't change version), while there is 0.7.7 version already.

**Comment by jayarjo** [comment]
What is UA string for Firefox 41?

**Comment by nazar-pc** [comment]
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0`

**Comment by jayarjo** [comment]
We've updated ua-parser-js to version 0.7.7, simply forgot to update the comment.

**Comment by nazar-pc** [comment]
Thanks!
