### ISSUE TITLE
When use Flash with the File Picker sample, the readAsBinaryString and readAsArrayBuffer call throws error on the selected file

### ISSUE THREAD

**Issue by imgen** [moxiecode/moxie#133]
I followed this example
https://github.com/moxiecode/moxie/wiki/File-Picker
and it works for selecting file, but when I tried to read the selected file using the *FileReader* api's readAsBinaryString, on Chrome and IE11, they both throws error saying the file is not a Blob file. Why is that? If I use the native file picker, there isn't this issue.

**Comment by jayarjo** [comment]
Unfortunately you cannot read it with _native_ FileReader. But you can use mOxies [FileReader](https://github.com/moxiecode/moxie/wiki/FileReader), which basically follows the same API.

**Comment by imgen** [comment]
How do I read with mOxie's FileReader? Forgive me for being dumb, but the documentation didn't state how to use mOxie's FileReader, at least I didn't see an example. Shouldn't the mOxie file picker automatically fall back to use the native file picker when File API is available?

**Comment by jayarjo** [comment]
To make it work as _native_ we would have to override the native File API to have the decision making layer in there somewhere, even when File API was present and fully functional in the browser. We chose to namespace it and structure it as parallel implementation following the same API (where possible).

To read the file as binary string through mOxies FileReader, you can do:

```javascript
var fi = new mOxie.FileInput('pickfiles');

fi.onchange = function() {
    var fr = new mOxie.FileReader();

    fr.onload = function() {
        console.info(this.result); // do something to the binary representation
    };

    fr.onloadend = function() {
        fr.destroy(); // and destroy when not required to assist garbage collection
    };

    fr.readAsBinaryString(this.files[0]);
};

fi.init();
```

**Comment by v1r** [comment]
not working with IE9 using flash..
onloadend not triggered.. 
when calling readAsBinaryString again, onloadend will output null.. 
any help will be very apprciated
Snipper : 
 mOxie.Env.swf_url = './resources/js/flash/Moxie.min.swf';
                var fileInput = new mOxie.FileInput({
                    runtimes: 'flash, silverligth,html4',
                    browse_button: "file-picker" 
                    multiple: true
                });

                fileInput.onchange = function(){
                    var file = fileInput.files[0];
                    var reader = new mOxie.FileReader();
                    reader.onloadend = function() {
                        dump(reader.result);
                    };

                    reader.onerror = function() {
                      dump( "read as binary failed"); 
                    };
                    reader.readAsBinaryString(file);

                };
 
                fileInput.init();

**Comment by jayarjo** [comment]
@v1r what does dump function do?

Here's a fiddle, that reads an image with `readAsBinaryString`, then converts it to data url and embeds as image: http://play.plupload.com/g66J_.
