### ISSUE TITLE
Provide unminified js script

### ISSUE THREAD

**Issue by willprice** [moxiecode/moxie#136]
Hi,

It'd be great if moxie provided an unminified version of itself on bower since some applications strip `-min` prefixes on debug builds (for easier debugging!) but this breaks with moxie since no `moxie.js` file is provided.

**Comment by jayarjo** [comment]
It took ridiculously long, but I've included it now in [v1.5.1](https://github.com/moxiecode/moxie/releases/tag/v1.5.1). Sorry, not a Bower-man at all (didn't even realise the importance). But then you could simply do a pull request.
