### ISSUE TITLE
Supported browers.... where are the docs?

### ISSUE THREAD

**Issue by levancho** [moxiecode/moxie#138]
I have not found anywhere that  it says which browsers are officially support, and I am highly doubtfull that IE8 is supported especially FILE api, can you confirm that we can use his lib to implement file chunking in IE8 ? if non, why is not documented anywhere? why there is no  browser support matrix anywhere?

**Comment by jayarjo** [comment]
We support all browsers. All the way down to IE6. File API is available, via [mOxie components](https://github.com/moxiecode/moxie/wiki). You can chunk files in IE8 with Flash or Silverlight runtime. But it depends what is your purpose there.

Here you can find the writeup of all capabilities and operational modes (with important footnotes): [Required Features](https://github.com/moxiecode/plupload/wiki/Required-Features).

**Comment by levancho** [comment]
Hi thanks for reply, ...

well I have to challenge   "chunking files in flash".. that  is not really a feasible options, think about it, flash runtime does not support file streaming (besides AIR) that means, I have to load whole file into memory and then chunk it, which defeats the purpose, if I have large file 1-3GB I will run out of memory before chunking even starts,since whole file has to be loaded into flash player.
I do not know how silverlight handles it, but I assume the same way. so technically saying those are not solutions. well unless file is relatively small which kind of defeats a  purpose of chunking file, why whould someone want to chunk small file? :)

**Comment by jayarjo** [comment]
Silverlight doesn't have this issue. And for Flash you can simply ignore chunking. Big files upload just fine.

**Comment by levancho** [comment]
it is not flash, its issue with most of the J2EE containers prior to Servlet 3.0 that have  problem with threads taking long time to finish ... for Example Weblogic ... 
 for me upgrade is not an option ...neither is silverlight,business users do not have silverlight installed.

as Our application is large Flex portal, users want 3GB file upgrade support ... without chunking that's not possible ... weblogic falls apart and monitoring tools are screaming their lungs out about thread being blocked etc .... 

anyways ...

I ended up forking old google project  and rewriting it.
https://github.com/levancho/JLFUploaderX2
