### ISSUE TITLE
mOxie.FileDrop events (dragenter,dragLeave) bubble

### ISSUE THREAD

**Issue by JohnRSim** [moxiecode/moxie#140]
If I drag something over #someDOM the ondragleave event is called even though I am still over #dropRegion filedrop area.

I can drop into someDOM and ondrop event is called - so it is possible if I drag over #someDOM for the ondragleave not to be called as I'm still in the #dropRegion container but hovering over a different layer. 
```javascript
var fileDrop = new mOxie.FileDrop('dropRegion');
```
```html
<div id="dropRegion" style="width:20px;height:20px;">
    <div id="someDOM" style="width:10px;height:10px;"></div>
</div>
```

**Comment by aik099** [comment]
This happens in any browser/os or a specific combination of browser+os?

**Comment by JohnRSim** [comment]
I have only tried in Chrome 45.0.2454.37 beta-m (64-bit) at the moment in win 8.1
