### ISSUE TITLE
UID not matching file.uid after onload event.

### ISSUE THREAD

**Issue by JohnRSim** [moxiecode/moxie#141]
If I use moxie to upload 1 file 
the file.uid is this - "uid_19tpoeje66pj1hbd1aih12otadvb"

But when I take a look at the xhr the UID has changed is this correct?

```javascript
xhr.onload = function(data) {
    console.log(data.target.uid);
}
```

Running win8.1 Chrome Version 45.0.2454.78 beta-m (64-bit) 
Moxie 1.4.1

**Comment by jayarjo** [comment]
`data.target` in your case is `xhr` instance, not `file`, so `uid`s will be different, as they are different objects.

**Comment by JohnRSim** [comment]
That makes sense - thanks Jayarjo.

If you do a multiple upload how do you know which document has been uploaded?
Is there anything in the response I can tie into? Or is the best process to tie in an additional param to the response?

Thanks
J.

**Comment by jayarjo** [comment]
Our implementation simply follows standard XMLHttpRequest specs. So I guess there is nothing in the event that you can tie to, unless you pass something back from the server. In case you didn't plan to do it manually, you should consider using [Plupload](https://github.com/moxiecode/plupload), that does just that, by encapsulating file uploading logic into easy to use class.

**Comment by jayarjo** [comment]
I will close this one.
