### ISSUE TITLE
cannot initiate silverlight client mode

### ISSUE THREAD

**Issue by schizotybalt** [moxiecode/moxie#143]
this isn't an actual issue, but i can't infer from the documentation how i'm supposed to initialize the silverlight runtime in client mode.  my custom HTTP response headers aren't returned in browser mode using IE 9 as the documentation states.

i'm away from my dev machine but i've tried reassigning a new silverlight runtime obj as follows (probably seems idiotic to anyone who's been working with this plugin for more than a day, unlike myself)

var silverlightconstructor=moXie.getConstructor("silverlight");
moXie.addConstructor("silverlight", silverlightconstructor({return_response_headers: true})); 

the firefox console gives an error similar to "TypeError: constructor is not a constructor"

**Comment by jayarjo** [comment]
Basically you pass options that control this (among other things) as the second argument to [XMLHttpRequest.send() method](https://github.com/moxiecode/moxie/wiki/XMLHttpRequest#send-method-dataoptions).

```javascript
var xhr = new mOxie.XMLHttpRequest();
// ...
xhr.send(file, {
    required_caps: {
        return_response_headers: true
    }
});

```
