### ISSUE TITLE
Moxie example fails to function. Are there any further examples of using moxie?

### ISSUE THREAD

**Issue by patrickclancy** [moxiecode/moxie#144]
Hello 

I followed these steps to use moxie. 
* added the moxie.js javascript file to the HEAD of a HTML page
* defined the swf file location with mOxie.Env.swf_url 
* used the example HTML/Script snippet on this page. https://github.com/moxiecode/moxie/wiki/File-Picker

But moxie doesn't appear to be working.

When I load the page I get "Instantiating FileInput..." output to the console. But clicking the "Browse..." link does nothing. No errors, no console logs. What should happen when clicking the link in the example?

Is there a working or complete example of moxie?

**Comment by patrickclancy** [comment]
Here is some more information. In Chome I'm seeing this error. If I delete line 7391 from moxie.js my demo example works. 

moxie.js:7391 Uncaught ReferenceError: Â is not defined(anonymous function) @ moxie.js:7391(anonymous function) @ moxie.js:55require @ moxie.js:38define @ moxie.js:54(anonymous function) @ moxie.js:7379(anonymous function) @ moxie.js:11114
test.html:27 Uncaught ReferenceError: mOxie is not defined(anonymous function) @ test.html:27

**Comment by jayarjo** [comment]
Maybe this playground will help: http://play.mytunes.ge/g6aJ6/2.
