### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by anthonyettinger** [moxiecode/moxie#145]
I did `bower install moxie` and included the `./bin/js/moxie.js` file in my `index.html`...but I still get this error in Safari 9 console:

```
FileConstructor is not a constructor (evaluating 'new File([data.data], fileName, { type: "text/plain" })')
```

**Comment by jayarjo** [comment]
This is not the Plupload error or the error one can fix with Plupload. We provide wrappers for `FileInput`, `FileReader`, `File`, etc under the mOxie namespace.

Check this playground for example: http://play.mytunes.ge/g6aJ6/2.
