### ISSUE TITLE
Runtime 'flash' failed to initialize

### ISSUE THREAD

**Issue by agile116** [moxiecode/moxie#146]
Hi All,

I have the following code snipet to pick an image file, flash runtime failed on all browsers.

```html
<script type="text/javascript" src="js/moxie.js"></script>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript">
	mOxie.Env.swf_url = 'flash/Moxie.swf';
</script>
var fileInput = new mOxie.FileInput({
        runtime_order: 'flash',
        browse_button: 'file-picker',
        accept: 'image/jpeg,image/jpg,image/png,image/gif'
    });

    fileInput.onchange = (e) => {
      let reader = new mOxie.FileReader();
      console.log('reader:',reader);
      let file = e.target.files[0];
      console.log(file);
      console.log('file: ',file.type);
      reader.onloadend = () => {
        console.log('result: ',reader.result);
      }

      reader.readAsDataURL(file)
    };

    fileInput.init(); 
```

I found that in all other Runtimes such as html5, html4, there is a statement in the init() method to trigger Init, this.trigger("Init"); which is the only place I saw to set runtime initialized to true, code below:
runtime.bind('Init', function() {
	// mark runtime as initialized
	runtime.initialized = true;
But FlashRuntime doesn't have this statement, so how does it set the initialized attribute to true? Code snippet is welcome.

I tried to add this statement in the init() method of FlashRuntime, it was initiated and I was able to select a file, but failed to get e.target.files[0], it is undefined.

Please help me! Thanks.

**Comment by jayarjo** [comment]
Seems to work fine, here: http://play.mytunes.ge/g6aJ7/5. Make sure that you provide a proper path in `mOxie.Env.swf_url`.
