### ISSUE TITLE
how can i load specific part of a file (for ajax)?

### ISSUE THREAD

**Issue by re2953** [moxiecode/moxie#147]
var fileInput = new mOxie.FileInput({
        	runtime_order: 'html5,flash',
            browse_button: 'file-picker', // or document.getElementById('file-picker')
            accept: [
                {title: "Images", extensions: "iso,txt,chm,jpg,gif,png,zip,txz,gz,vdi"} // accept only images // i add a 20G vdi file for test
            ]
        });

        fileInput.onchange = function(e) {
        	if (e.target.files == null || e.target.files.length == 0) {
        		return;
        	}
        	var fileClone = e.target.files[0].slice(1005, 2000, 'part');
        	
        	var reader = new mOxie.FileReader();
        	reader.addEventListener("loadend", function() {
        		alert(reader.result);
        	   // reader.result contains the contents of blob as a typed array
        	});
        	reader.readAsBinaryString(fileClone);
        	
        };

        fileInput.init(); // initialize

flash just loads the file (complete) into memory

**Comment by jayarjo** [comment]
Yes, that's what flash does. There's no way around it currently. In order to slice the file, Flash requires the whole thing in memory.
