### ISSUE TITLE
manually call browse_button.click() not working on some browsers

### ISSUE THREAD

**Issue by netweaver** [moxiecode/moxie#150]
hi
i found that manually call browse_button.click() on some browsers( such as windows ie6-9, ios safari)  is not working (can not open file select dialog) .   i've tried different runtimes, 

it is ok on chrome, ie11

**Comment by netweaver** [comment]
i test it with plupload

**Comment by jayarjo** [comment]
Well, yes. That's how it used to be in old times. One wasn't able to invoke file dialog with the manual `click()`. What is the question exactly?
