### ISSUE TITLE
SCRIPT5009: 'FormData' is undefined in IE9 with Moxie

### ISSUE THREAD

**Issue by ghost** [moxiecode/moxie#152]
First time moxie user here, I build moxie with `jake mkjs[file/FileInput,xhr/XMLHttpRequest] runtimes=html5,flash` and included in my code:
```
<!--[if IE 9]>
      <script type="text/javascript" src="/static/shims/moxie.min.js"></script>
      <script>mOxie.Env.swf_url = '/static/shims/Moxie.min.swf';</script>
<![endif]-->
<script type="text/javascript" src="/dist/js/web.js"></script>
```

But on IE 9, I still have this console error:

```
SCRIPT5009: 'FormData' is undefined
web.js, line 58 character 13934
```

The FormData call in question is just request/form-data code that redirect form-data to use the global FormData object in the browser, and works without any issue in IE > 9, https://github.com/form-data/form-data/blob/master/lib/browser.js

Simple console test in IE9 gives:
```
>> console.log("Hello World")
LOG: Hello World
>> console.log(window.FormData)
LOG: undefined
```

Further moxie seems to be getting loaded since changing the script path triggers a console error as well.

Any idea what could be wrong?

**Comment by jayarjo** [comment]
We do not alter native DOM. All mOxie components are namespaced. Try: `mOxie.FormData`. Also it probably has no sense to use it without the rest of mOxies components.
