### ISSUE TITLE
Use moxie with webpack throw  a error

### ISSUE THREAD

**Issue by towersxu** [moxiecode/moxie#154]
hi,when I use moxie with webpack,chrome throw a error:
  ```
Uncaught TypeError: Cannot read property 'moxie' of undefined
  expose	@	moxie.js:85
  (anonymous function)	@	moxie.js:21
  webpackJsonp.135	@	moxie.js:21
```
I  changed moxie source code `this` to `window`,  it works fine.
```javascript
(function(exports) {
    ...
})(window)
```

**Comment by lanria990** [comment]
good ,webpack  es6 moudle `this ==undefined`

**Comment by learntocoderight** [comment]
In addition to the changed code above, I also had to change the following piece of code from `this` to `window`.

`expose(...)(window);`

**Comment by jayarjo** [comment]
I'm not a Webpack use myself. Is it useful somehow? Do you guys know why `this == undefined` there?

**Comment by towersxu** [comment]
@jayarjo now,I think  [imports-loader](https://webpack.js.org/guides/shimming/#imports-loader) can resolve this problem.

**Comment by jayarjo** [comment]
@towersxu this should be solved by now. Are you experiencing any problems with webpack +moxie?

**Comment by zZengwork** [comment]
(function(exports) {
    ...
})(window)

Where is this code specific please？？？？
