### ISSUE TITLE
Flash and silverlight minify version do not compatible with IE8. 

### ISSUE THREAD

**Issue by elantion** [moxiecode/moxie#155]
I saw debug log show IE8 use siverlight initialization, it shown success. I can select image, but I can not read any image and embed to any element. After a lot of testing, but no luck.
Suddenly, I switch the flash and siverlight minify version to original version. Luckily, everything OK. So I guess there are some problem with flash and siverlight minify version.

**Comment by jayarjo** [comment]
Do you mean `min.swf` and `min.xap` versions? They simply do not contain image manipulation logic. This is for those cases when only uploading functionality is required. `min` versions are much less in size and load much faster. But you cannot manipulate images with them.
