### ISSUE TITLE
Memory leak in IE

### ISSUE THREAD

**Issue by hichemhlm** [moxiecode/moxie#157]
When you destroy a HTML5Image object in IE OR Edge the image object stay on memory and not get collected by the garbage collector.
ex : 
`var _img = new image();
_img.load = function(){
...
}
_img.src = '...';
_img = null;`

This is blocking issue when you deal with lot of images with high quality.

**Comment by jayarjo** [comment]
If you create a pull request, I will merge this in.

**Comment by jayarjo** [comment]
Merged it myself here: https://github.com/moxiecode/moxie/commit/f51cea4328623c87f960b8e3314d39a6916e867b. Thanks!

**Comment by jayarjo** [comment]
Oh crap. Took author from that repo on your account and turns out it wasn't even yours. Nah...

You should have filed pull request there. Now your contribution is authored by some random guy :/

**Comment by hichemhlm** [comment]
You shouldn’t merged it was closed :)
