### ISSUE TITLE
v1.4 stable release

### ISSUE THREAD

**Issue by chrisminett** [moxiecode/moxie#161]
Question: Can you please do a stable release for v1.4.x soon, and integrate it into Plupload?

We're using Plupload to filter by extension to only allow HTML files, setting the `filters.extensions` config to `"htm,html"`. In Firefox on Windows this only allows _.htm_ and on OS X it only allows _.html_.

This was fixed over a year ago in a1b87942821e51cad0385231a991f672995ccf70 by allowing Firefox to filter by extension rather than MIME, which in turn is in v1.4.1 marked as pre-release.

I guess that in order to get this fix (which has been available in FF since early 2015) into Plupload, a stable release is needed here first.

**Comment by jayarjo** [comment]
Plupload v2.2.0 includes v1.5.1 now.
