### ISSUE TITLE
Can I Use Moxie If I Sell My WebApp?

### ISSUE THREAD

**Issue by opticyclic** [moxiecode/moxie#163]
I have a java web app that I sell.

I now have a need to upload files to the browser without round tripping to the server.
In order to not exclude IE8 and IE9 I need a FileReader shim.

Can I use Moxie in this case or will the AGPL require me to open source my whole application?

**Comment by jayarjo** [comment]
You could purchase OEM license I guess. You can read more about licenses [here](https://www.ephox.com/legal/).
