### ISSUE TITLE
Bug. Runtime flash and plupload.addFile() not working

### ISSUE THREAD

**Issue by kudlacekv** [moxiecode/moxie#170]
Steps to reproduce bug:
1) use simple project with plupload
2) configure plupload to use runtime flash
3) on page create input type file
4) in js call plupload.addFile(document.getElementById('inputFile').files[0])
5) try upload

Flash create and send multipart form request but without file content!

Reason is Moxie flash src/com/XMLHttpRequest.as
```
public function appendBlob(name:String, blob:*, fileName:String = null) : void
{			
	_multipart = true;
	_blobName = fileName || 'blob' + new Date().getTime();
	if (typeof blob === 'string') {
		blob = Moxie.compFactory.get(blob);
		Moxie.log('after Moxie.compFactory.get');
		Moxie.log(blob);
		if (!fileName && blob is File && blob.hasOwnProperty('name')) { 
			_blobName = blob.name;
		} 
	}
			
	_blob = blob;
	_blobFieldName = name;						
}
```
In situation described at top of issue, typeof blob is string, but Moxie.compFactory(blob) return false. I know it is related to created flash object and separate input file vs ruid, but I really don't know how to fix that. I haven't any experiences with ActionScript before. It works when I read file content by javascript and use uploader.addFile with moxie blob object, but I can't use javascript readfile api in IE 9.

Any advices?

**Comment by jayarjo** [comment]
Why don't you simply instantiate moxies `FileInput` object on that additional `input[type="file"]`? Then you will have compatible File object, that you will be able to add with `plupload.addFile`.

The way you describe - it won't work. There's no fix for that in IE9. That's plupload/moxie was created in first place.

**Comment by kudlacekv** [comment]
Yep, you are right. I misunderstood whole idea of moxie. So I read file by moxie FileInput and moxie FileReader then modify content and send. Job done.

Thanks for your help.
