### ISSUE TITLE
Infinite events cycle on Angular 2 + IE9

### ISSUE THREAD

**Issue by irbian** [moxiecode/moxie#173]
Hi!

Tried to use the component on a Angular 2 App. After some meddling I could load the library but now, just creating a new FileInput generates a infinite cycle that makes the page irresponsive.

    this.fileInput = new window.FileInput({
                runtime_order: 'flash,html5',
                browse_button: "filepicker",
                accept: [
                    { title: "Images", extensions: "jpg,gif,png" } // accept only images
                ]
            });

Anyone have found this problem/has been lucky making work this on Angular 2?

Regards

**Comment by jayarjo** [comment]
Can you organize a case online, here for example: http://play.plupload.com?

**Comment by irbian** [comment]
Gonna be difficult, it is a angular 2 component

I turned on the debug and I saw 5 or 6 events cycling once and again, triggering with different uid each time

**Comment by jayarjo** [comment]
@irbian without the case we won't be able to troubleshoot it.

**Comment by jayarjo** [comment]
Btw, we do not even expose FileInput like that, so how do you even refer to it through `window.FileInput`?

**Comment by irbian** [comment]
ey

I´m far from my code now, but the idea is:

I make it work with this example (https://github.com/moxiecode/moxie/issues/26). Adapted, because mOxie.FileReader is not there (is now on moxie.file.FileReader)

Probably part of my problems are related with the fact that I´m a newbie on Angular 2 but the main idea was encapsulating the library on a component. From memory, I have something like this:

    
    constructor( ) {
	window.moxie = require('moxie');
	if (!window.FileReader) {
		window.FileReader = window.moxie.file.FileReader;
		window.XMLHttpRequest  = window.moxie.file.XMLHttpRequest;		
	}
	window.FileInput = window.moxie.file.FileInput;
    }

    ngOnInit() {
	
	this.fileInput = new window.FileInput({
		runtime_order: 'flash,html5',
		browse_button: "filepicker",
		accept: [
			{ title: "Images", extensions: "jpg,gif,png" } // accept only images
		]
	});
	
	// Commented, the cycle starts just with the new FileInput
	/*
	
	this.fileInput.onchange = function (e) {
		var file = e.target.files[0];

		showPreview(file, "#preview");

		ajax("post", "/something", getFile(file), function () {
			console.log("success");
		}, function (e) {
			console.log("error", JSON.stringify(e));
		});
	};
	this.fileInput.init();*/
    }

**Comment by jayarjo** [comment]
Firstly `moxie`'s FileReader is not direct equivalent of native FileReader, mainly because of third party shims that cannot be seamlessly wrapped. And neither XMLHttpRequest.

Also, globalising libraries is not exactly a valid way of encapsulating them up in components in Angular ecosystem (it's actually an opposite). 

Sorry, what you observe is not something that I can reproduce here, so we need a case with the problem manifesting itself. Then we will be able to treat it one way or another.

**Comment by irbian** [comment]
while I have the chance to make a reproducible case, what would be your approach? I follow this one (https://github.com/moxiecode/moxie/issues/26) because is the more similar example of what I want to use, use the readasdataurl method

I know that that code is an antipattern, but it didn´t start that way. If I recall property I had problems on IE9 because the library tried to invoke global XMLHttpRequest

In the end, what I want to do use the readasdataurl method, if you know a better approach, please share it :D

**Comment by irbian** [comment]
For the record, after using your lastest commits AND fixing the typo AND using an encapsulated approach (via require, just as you pointed at first) now is properly working :D I hace some cleanup to do first, but this is promising

Would you mind to release this version so I can install it via npm?

**Comment by jayarjo** [comment]
Yes. Basically preparing a bugfix release. Need to address couple more issues though.

**Comment by irbian** [comment]
Would you mind to give me an estimated date? So I can know if I wait for it or move it to our internal repo

**Comment by jayarjo** [comment]
I've just pushed v1.5.4 to npm.

**Comment by irbian** [comment]
Thank you!
