### ISSUE TITLE
Suggestion: Modifying the XMLHttpRequest Api

### ISSUE THREAD

**Issue by irbian** [moxiecode/moxie#174]
Hi!

Would like to know your opinion about setting the XMLHttpRequest options on the constructor instead of the method send.

In my particular case, Angular 2 allow to inject a XMLHttpRequest class to be wrapped by his http library. This feature is for injecting a MockXMLHttpRequest but I´m using to inject your polyfill if needed. As it is now, I have to modify the whole http library to modify where the send method is called

**Comment by jayarjo** [comment]
If you are using it on it's own, you could I guess.

**Comment by irbian** [comment]
After revisiting the code, I think that maybe a better/simpler approach would be to connect to the blob runtime, the same way you do here to the FileReader https://github.com/moxiecode/moxie/blob/master/src/javascript/file/FileReader.js#L230
