### ISSUE TITLE
How to get a blob as dataurl?

### ISSUE THREAD

**Issue by irbian** [moxiecode/moxie#176]
Hi!

I would like to create a link with a response blob as content, so I can click on it to download it. It's possible? My tests hasn´t been succesful

**Comment by jayarjo** [comment]
No. Flash and Silverlight do not support anything like this. And for HTML5 runtime you could do it yourself, by feeding source blob to `URL.createObjectURL()`.

**Comment by irbian** [comment]
Thanks for your answer :)
