### ISSUE TITLE
How to install it with flash?

### ISSUE THREAD

**Issue by vit-panchuk** [moxiecode/moxie#177]
I suppose something changed and Readme instructions are not actual. Could you help me to provide flash fallback to FileReader with this lib?
In readme:

```
<script src="moxie.js"></script>
<script>mOxie.Env.swf_url = './flash/Moxie.min.swf';</script>
```

In console:
```
Uncaught ReferenceError: mOxie is not defined
```

**Comment by jayarjo** [comment]
Try: `moxie.core.utils.Env.swf_url`. I will fix readme.
