### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by kottenator** [moxiecode/moxie#89]
Hi!

I'm going to use mOxie, but the license is not clear to me. 

In the `license.txt` there is a GPL v2 license. But in the `README.md` you say: 

    Code that you contribute will automatically be licensed under the LGPL, 
    but will not be limited to LGPL

And there is nothing about commercial usage of the mOxie.

My questions are:
- Q1: if I'm going to use mOxie in a commercial project, what is the license for it?
- Q2: if I'm going to use mOxie in my open-source project, will it be under LGPL and I could use my open-source project in a commercial project as LGPL-licensed library?
- Q3: don't you want to switch to MIT license, as most of popular open-source frameworks do? :)

**Comment by jayarjo** [comment]
I was expecting someone more competent to answer this, but apparently they are busy with something else. I guess commercial usage falls under the following conditions, just like the Plupload: http://www.plupload.com/license/oem.
