### ISSUE TITLE
Please publish an NPM module

### ISSUE THREAD

**Issue by tarjei** [moxiecode/moxie#93]
Hi - thanks for a great lib!

Modern JS packages use NPM for publishing packages. It would be great if you could publish CommonJS compatible versions of Moxie to NPM.

**Comment by jgrigg** [comment]
+1

**Comment by egmanoj** [comment]
+1

**Comment by jayarjo** [comment]
mOxie is on npm registry: https://www.npmjs.com/package/mOxie.
