### ISSUE TITLE
Using FormData erases headers of XMLHttpRequest in IE 7,8,9

### ISSUE THREAD

**Issue by pix666** [moxiecode/moxie#99]
I found this problem from plupload plugin.

This simple code not sent header "Test" in IE 7,8,9.

```
xhr = new mOxie.XMLHttpRequest();
xhr.open('POST', '/', true);

var form = new mOxie.FormData();
form.append('name', 'pix');

xhr.setRequestHeader('Test', 'Hello, World!');
xhr.send(form);
```

P.S. if I send simple text - it works:

```
xhr = new mOxie.XMLHttpRequest();
xhr.open('POST', '/', true);

xhr.setRequestHeader('Test', 'Hello, World!');
xhr.send('all good');
```

**Comment by irbian** [comment]
Looks like this is still a problem

**Comment by jayarjo** [comment]
@irbian exactly that, or similar?

**Comment by irbian** [comment]
At this moment, I´ll be honest, I don´t know. I have spend the whole day triying to make this work one IE9 and this was one of the symptoms I got. In the end I arrived to the comment I explain here https://github.com/moxiecode/moxie/issues/125 . If I found again the proper combination that trigger this problem, I´ll let you know
